version: "3.8"

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_portfolio
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "portfolio_db"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "devpass"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"           
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h","localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ../..                       
      dockerfile: infra/docker/Dockerfile.backend
    image: sarthak-backend:v1
    container_name: portfolio_backend
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: dev
      DB_PASSWORD: devpass
      DB_NAME: portfolio_db
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.frontend-from-build
    image: sarthak-frontend:v1
    container_name: portfolio_frontend
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  mysql-data:
