apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio-devops
type: Opaque
data:
  mysql-user: cm9vdA==  
  mysql-password: c2FydGhha0AxMjM=
  mysql-root-password: c2FydGhha0AxMjM=
  jwt-secret: c3VwZXItc2VjcmV0LWtleS1mb3Itand0