apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio-devops
type: Opaque
data:
  # Base64 encoded 'root' (Clean, NO trailing newline)
  mysql-user: cm9vdA== 
  
  # Base64 encoded 'sarthak@123' 
  mysql-password: c2FydGhha0AxMjM= 
  
  # Base64 encoded 'super-secret-key-for-jwt'
  jwt-secret: c3VwZXItc2VjcmV0LWtleS1mb3Itam90