apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio-devops
type: Opaque
data:
  # The database user (e.g., 'root')
  mysql-user: cm9vdAo= # Base64 encoded 'root'
  
  # The database password (e.g., 'password')
  mysql-password: cGFzc3dvcmQK # Base64 encoded 'password' 
  
  # JWT Secret Key for the Node.js backend (Replace with your own long random key!)
  jwt-secret: c3VwZXItc2VjcmV0LWtleS1mb3Itam90 # Base64 encoded 'super-secret-key-for-jwt'